version: '3.9'
services:
  backend:
    build: ./backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend

